AWSTemplateFormatVersion: 2010-09-09
Description: AWS Athena resources
Resources:
  MyAthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      WorkGroupConfigurationUpdates:
        ResultConfigurationUpdates:
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
      Name: MyCustomWorkGroup
      Description: My WorkGroup
      State: ENABLED
      Tags:
        - Key: key1
          Value: value1
        - Key: key2
          Value: value2
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation: 's3://path/to/my/bucket/'