AWSTemplateFormatVersion: 2010-09-09
Description: Create Basic Notebook
Resources:
  BasicNotebookInstance:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      KmsKeyId: asdasd
      SubnetId: subnet-01234567890abcdef
      DirectInternetAccess: Disabled
      InstanceType: ml.t2.large
      RoleArn: !GetAtt 
        - ExecutionRole
        - Arn
  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerFullAccess'
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance
