AWSTemplateFormatVersion: 2010-09-09
Resources:
  Prod:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      CacheClusterEnabled: 'true'
      TracingEnabled: 'true'
      StageName: Prod
      Description: Prod Stage
      RestApiId: !Ref MyRestApi
      DeploymentId: !Ref TestDeployment
      DocumentationVersion: !Ref MyDocumentationVersion
      ClientCertificateId: !Ref ClientCertificate
      Variables:
        Stack: Prod
      MethodSettings:
        - CacheDataEncrypted: 'true'
          CachingEnabled: 'true'
          LoggingLevel: INFO
          ResourcePath: /
          HttpMethod: GET
          MetricsEnabled: 'true'
          DataTraceEnabled: 'false'
        - CacheDataEncrypted: 'true'
          CachingEnabled: 'true'
          LoggingLevel: INFO
          ResourcePath: /stack
          HttpMethod: POST
          MetricsEnabled: 'true'
          DataTraceEnabled: 'false'
          ThrottlingBurstLimit: '999'
        - CacheDataEncrypted: 'true'
          CachingEnabled: 'true'
          LoggingLevel: INFO
          ResourcePath: /stack
          HttpMethod: GET
          MetricsEnabled: 'true'
          DataTraceEnabled: 'false'
          ThrottlingBurstLimit: '555'
