AWSTemplateFormatVersion: 2010-09-09
Resources:
 mydetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: false
        FindingPublishingFrequency: FIFTEEN_MINUTES
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration.