AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyWebACL: 
    Type: "AWS::WAFRegional::WebACL"
    Properties: 
      Name: "WebACL to block restricted countries"
      DefaultAction: 
        Type: "ALLOW"
      MetricName: "MyWebACL"
      Rules: 
        - 
          Action: 
            Type: "BLOCK"
          Priority: 1
          RuleId: 
            Ref: "MyGeoMatchRule"
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration.