name: 'IAC Assist Terraform Action'

on: 
  workflow_dispatch:
    inputs:
      reason:
        description: 'Do you want to process all files?'
        required: false
        default: 'No - Only Last Commit Files'
        type: choice
        options:
        - Yes - All Files
        - No - Only Last Commit Files
  push:
    branches: ["main"]

jobs:
  
  analysis:
    permissions: write-all
    runs-on: [self-hosted]
   
    steps:
    - name: checkout version
      uses: actions/checkout@v3
      
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Clone parser repo
      uses: actions/checkout@v3
      with:
        repository: DaveChintan/tmhclparser
        token: ${{ secrets.GH_PAT }}
        path: parser
        ref: filefolderimplementation
        
    - name: Get all changed files
      id: changed-files
      uses: tj-actions/changed-files@v36
      with:
        separator: ","
        json: true
        write_output_files: true
        
    - name: Update env
      run: |
        echo "CHANGED_FILES=${{ steps.changed-files.outputs.all_modified_files }}" >> "$GITHUB_ENV"
        echo "FULL_SCAN=${{ github.event.inputs.reason == 'Yes - All Files' }}" >> "$GITHUB_ENV"
        echo "API_KEY=${{ secrets.API_KEY }}" >> "$GITHUB_ENV"
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> "$GITHUB_ENV"
        
        
    - name: Run parser
      run: |
        node ./parser/main.js
         
    - name: Store logs results as Build Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: ./logs/

    - name: List Files
      run: |
        cd ./SarifFiles && ls -all
        ls -all

    - name: Check for sarif files
      id: check-sarif
      run: |
        if [[ -d ./SarifFiles && -n "$(ls -A ./SarifFiles)" ]]; then 
          echo "directory not exists"
          echo "::set-output name=empty::true
        else
          echo "directory exists"
          echo "::set-output name=empty::false
        fi

        #if [[ "$(ls -A ./SarifFiles/)" ]]; then
        #  echo "::set-output name=empty::false
        #else
        #  echo "::set-output name=empty::true
      
    - name: Store SARIF results as Build Artifact
      if: steps.check-sarif.outputs.empty == 'false' 
      uses: actions/upload-artifact@v1
      with:
        name: IAC_SARIF_Results
        path: ./SarifFiles/
     
    -  name: Upload SARIF results to Github
       if: steps.check-sarif.outputs.empty == 'false' 
       uses: github/codeql-action/upload-sarif@v2      
       with:
         sarif_file: ./SarifFiles/     
